Host = ""

[Mysql]
Host = "172.18.28.225"
#Host = "127.0.0.1"
User = "root"
Password = "dqf009."
DB = "heguang"
Port = "3306"

[Consul]
#Host = "127.0.0.1"
Host = "172.18.28.225"
Port = "8500"

[GRPC]
Host = "127.0.0.1"
Port = "50051"

